/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Cadastro;

import ColumnModel.ImpotracaoFaturaColumnModel;
import TableModel.FaturaTableModel;
import Uteis.CalendarComboBox;
import bean.cadastro.Categoria;
import bean.cadastro.ContasPagar;
import bean.cadastro.TipoConta;
import controlefinanceiro.cellEditor.ImportacaoFaturaCellEditor;
import controlefinanceiro.cellRenderer.ImportacaoFaturaCellRenderer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Thiago
 */
public class ImpotracaoFatura extends javax.swing.JDialog {

    /**
     * Creates new form ImpotracaoFatura
     */
    public ImpotracaoFatura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().getContentPane().setBackground(new java.awt.Color(215, 228, 242));
        jPanel2.setBackground(new java.awt.Color(215, 228, 242));
        jPanel1.setBackground(new java.awt.Color(215, 228, 242));
        jPanel3.setBackground(new java.awt.Color(215, 228, 242));
        jCmbVencimento.setSelectedItem(Uteis.Uteis.getData(new Date()));
        jTblFatura.setAutoCreateColumnsFromModel(false);
        jTblFatura.setColumnModel(new ImpotracaoFaturaColumnModel(jTblFatura.getFontMetrics(jTblFatura.getFont())));
        jTblFatura.getSelectionModel().addListSelectionListener(jTblFatura);

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "escape");
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblFatura = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnPesquisaTipoConta = new javax.swing.JButton();
        jBtnPesquisaCategoria = new javax.swing.JButton();
        jTxfTipoConta = new javax.swing.JTextField();
        jTxfCategoria = new javax.swing.JTextField();
        jBtnAplicarVencimento = new javax.swing.JButton();
        jCmbVencimento = new CalendarComboBox(true);
        jPanel3 = new javax.swing.JPanel();
        jBtnConfirmarImportacao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxfTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxfnovosRegistros = new javax.swing.JTextField();
        jTxfQtdTotalRegistros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Financeiro");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTblFatura.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTblFatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblFatura.setRowHeight(20);
        jScrollPane1.setViewportView(jTblFatura);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Tipo Conta");

        jLabel2.setText("Categoria");

        jBtnPesquisaTipoConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pesquisar.png"))); // NOI18N
        jBtnPesquisaTipoConta.setActionCommand("pesquisaTipoConta");

        jBtnPesquisaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pesquisar.png"))); // NOI18N
        jBtnPesquisaCategoria.setActionCommand("pesquisaCategoria");

        jTxfTipoConta.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jTxfCategoria.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jBtnAplicarVencimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1Entrar.png"))); // NOI18N
        jBtnAplicarVencimento.setActionCommand("aplicarVencimento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisaTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxfTipoConta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPesquisaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 600, Short.MAX_VALUE)
                .addComponent(jCmbVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAplicarVencimento)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jBtnPesquisaTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxfTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAplicarVencimento))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jBtnPesquisaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnConfirmarImportacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1Entrar.png"))); // NOI18N
        jBtnConfirmarImportacao.setText("Confirmar Impotracao");
        jBtnConfirmarImportacao.setActionCommand("confirmarImportacao");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Total:");

        jTxfTotal.setEditable(false);
        jTxfTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTxfTotal.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfTotal.setText("0,00");
        jTxfTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Novos:");

        jTxfnovosRegistros.setEditable(false);
        jTxfnovosRegistros.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfnovosRegistros.setText("0");

        jTxfQtdTotalRegistros.setEditable(false);
        jTxfQtdTotalRegistros.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfQtdTotalRegistros.setText("0");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Total:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jBtnConfirmarImportacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfnovosRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfQtdTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTxfQtdTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxfnovosRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTxfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBtnConfirmarImportacao))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setText("Importação de dados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        setSize(new java.awt.Dimension(1139, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImpotracaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImpotracaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImpotracaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImpotracaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImpotracaoFatura dialog = new ImpotracaoFatura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAplicarVencimento;
    private javax.swing.JButton jBtnConfirmarImportacao;
    private javax.swing.JButton jBtnPesquisaCategoria;
    private javax.swing.JButton jBtnPesquisaTipoConta;
    private javax.swing.JComboBox jCmbVencimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblFatura;
    private javax.swing.JTextField jTxfCategoria;
    private javax.swing.JTextField jTxfQtdTotalRegistros;
    private javax.swing.JTextField jTxfTipoConta;
    private javax.swing.JTextField jTxfTotal;
    private javax.swing.JTextField jTxfnovosRegistros;
    // End of variables declaration//GEN-END:variables

    public void addActionListerner(ActionListener actionListener) {
        jBtnPesquisaCategoria.addActionListener(actionListener);
        jBtnPesquisaTipoConta.addActionListener(actionListener);
        jBtnAplicarVencimento.addActionListener(actionListener);
        jBtnConfirmarImportacao.addActionListener(actionListener);
    }
    private Categoria categoria;
    private TipoConta tipoConta;

    public void setListaContas(List<ContasPagar> lst) {
        jTblFatura.setModel(new FaturaTableModel(lst));
        jTblFatura.setDefaultRenderer(ContasPagar.class, new ImportacaoFaturaCellRenderer(lst));
        double total = 0;
        for (ContasPagar c : lst) {
            total += c.getVALORCOMPRA();
        }
        jTxfTotal.setText(Uteis.Uteis.formatarMoeda(total));
    }

    public void setCellEditor(List<Categoria> lstCategoria) {
        jTblFatura.setDefaultEditor(ContasPagar.class, new ImportacaoFaturaCellEditor(lstCategoria));
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
        jTxfCategoria.setText(categoria.getIdCategoria() + " - " + categoria.getDescricaoCategoria());
        for (ContasPagar c : ((FaturaTableModel) jTblFatura.getModel()).getLista()) {
            c.setCategoria(categoria);
        }
        jTblFatura.repaint();
    }

    public void setTipoConta(TipoConta tipoConta) {
        this.tipoConta = tipoConta;
        jTxfTipoConta.setText(tipoConta.getIdTipo() + "-" + tipoConta.getDescricao());
        for (ContasPagar c : ((FaturaTableModel) jTblFatura.getModel()).getLista()) {
            c.setTipoConta(tipoConta);
        }
        jTblFatura.repaint();
    }

    public Date getDataVencimento() throws Exception {
        return Uteis.Uteis.getDate(jCmbVencimento.getSelectedItem().toString());
    }

    public void repaintTable() {
        jTblFatura.repaint();
    }

    public void setRegistros(int existentes, int novosRegistros) {
        jTxfnovosRegistros.setText(String.valueOf(existentes));
        jTxfQtdTotalRegistros.setText(String.valueOf(novosRegistros));
    }
}
