/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.principal;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import controlefinanceiro.Main;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author Thaigo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

        URL url = this.getClass().getResource("/controlefinanceiro/excel7.png");
        Image i = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(i);

        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "escape");
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        this.setExtendedState(NORMAL);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocation(0, 0);
        this.setSize( (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth(),(int)Toolkit.getDefaultToolkit().getScreenSize().getHeight()-50);
    }

    class ActionClose extends AbstractAction {

        public void actionPerformed(ActionEvent e) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnConta = new javax.swing.JButton();
        jBtnLancarContas = new javax.swing.JButton();
        jBtnRelacaoDeContas = new javax.swing.JButton();
        jBtnCategorias = new javax.swing.JButton();
        jBtnTipoDeConta = new javax.swing.JButton();
        jBtnRelatorios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnILocalizarBanco = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnIImportacaoFatura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Controle Financeiro");

        jBtnConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Conta.png"))); // NOI18N
        jBtnConta.setToolTipText("Conta");
        jBtnConta.setActionCommand("contaFinanceira");
        jToolBar1.add(jBtnConta);

        jBtnLancarContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lançar Conta.png"))); // NOI18N
        jBtnLancarContas.setToolTipText("Lançar Contas");
        jBtnLancarContas.setActionCommand("lancarContas");
        jToolBar1.add(jBtnLancarContas);

        jBtnRelacaoDeContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RelacaoDeContas.png"))); // NOI18N
        jBtnRelacaoDeContas.setToolTipText("Relação de Contas");
        jBtnRelacaoDeContas.setActionCommand("relacaoDeContas");
        jToolBar1.add(jBtnRelacaoDeContas);

        jBtnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Categoria.png"))); // NOI18N
        jBtnCategorias.setToolTipText("Categorias");
        jBtnCategorias.setActionCommand("lancamentoDeCategorias");
        jToolBar1.add(jBtnCategorias);

        jBtnTipoDeConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TipoDeContas.png"))); // NOI18N
        jBtnTipoDeConta.setToolTipText("Tipo de Contas");
        jBtnTipoDeConta.setActionCommand("consultaTipoDeContas");
        jToolBar1.add(jBtnTipoDeConta);

        jBtnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/graphic48.png"))); // NOI18N
        jBtnRelatorios.setToolTipText("Relatorios");
        jBtnRelatorios.setActionCommand("relatorios");
        jBtnRelatorios.setFocusable(false);
        jBtnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnRelatorios);

        jMenu1.setText("Cadastro");

        jMnILocalizarBanco.setText("Localizar Banco");
        jMnILocalizarBanco.setActionCommand("localizarBanco");
        jMenu1.add(jMnILocalizarBanco);

        jMenu3.setText("Aparencia");

        jMenuItem2.setText("Windows");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Quaqua (Azul)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem1.setText("Nimbus");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem4.setText("Metal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Nenhum");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        jMnIImportacaoFatura.setText("Importação Fatura");
        jMnIImportacaoFatura.setActionCommand("importacaoFatura");
        jMenu2.add(jMnIImportacaoFatura);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 519, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FileOutputStream arquivo;
        try {
            Main.config.setAparencia("Windows");
            XStream xStream = new XStream(new DomDriver("UTF-8"));
            arquivo = new FileOutputStream(System.getProperty("user.dir") + "/config.xml");
            xStream.toXML(Main.config, arquivo);
            arquivo.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Main.config.setAparencia("quaqua");
        FileOutputStream arquivo;
        try {
            XStream xStream = new XStream(new DomDriver("UTF-8"));
            arquivo = new FileOutputStream(System.getProperty("user.dir") + "/config.xml");
            xStream.toXML(Main.config, arquivo);
            arquivo.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Main.config.setAparencia("Nimbus");
        FileOutputStream arquivo;
        try {
            XStream xStream = new XStream(new DomDriver("UTF-8"));
            arquivo = new FileOutputStream(System.getProperty("user.dir") + "/config.xml");
            xStream.toXML(Main.config, arquivo);
            arquivo.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Main.config.setAparencia("Metal");
        FileOutputStream arquivo;
        try {
            XStream xStream = new XStream(new DomDriver("UTF-8"));
            arquivo = new FileOutputStream(System.getProperty("user.dir") + "/config.xml");
            xStream.toXML(Main.config, arquivo);
            arquivo.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Main.config.setAparencia("Metal");
        FileOutputStream arquivo;
        try {
            XStream xStream = new XStream(new DomDriver("UTF-8"));
            arquivo = new FileOutputStream(System.getProperty("user.dir") + "/config.xml");
            xStream.toXML(Main.config, arquivo);
            arquivo.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCategorias;
    private javax.swing.JButton jBtnConta;
    private javax.swing.JButton jBtnLancarContas;
    private javax.swing.JButton jBtnRelacaoDeContas;
    private javax.swing.JButton jBtnRelatorios;
    private javax.swing.JButton jBtnTipoDeConta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMnIImportacaoFatura;
    private javax.swing.JMenuItem jMnILocalizarBanco;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ActionListener actionSupport) {
        jBtnRelacaoDeContas.addActionListener(actionSupport);
        jBtnLancarContas.addActionListener(actionSupport);
        jBtnCategorias.addActionListener(actionSupport);
        jBtnConta.addActionListener(actionSupport);
        jBtnTipoDeConta.addActionListener(actionSupport);
        jMnILocalizarBanco.addActionListener(actionSupport);
        jBtnRelatorios.addActionListener(actionSupport);
        jMnIImportacaoFatura.addActionListener(actionSupport);
    }

}
