/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.movimento;

import Uteis.FieldListneterFormatandoValorMonetario;
import Uteis.UpperCaseValores;
import bean.cadastro.ContasPagar;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 *
 * @author Thiago
 */
public class BaixaParcialFrm extends javax.swing.JDialog {

    /**
     * Creates new form BaixaParcialFrm
     */
    public BaixaParcialFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTxfValorAbatido.addFocusListener(new FieldListneterFormatandoValorMonetario());
        jTxfValorAbatido.setDocument(new UpperCaseValores(12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBtnCofirma = new javax.swing.JButton();
        jBtnCancela = new javax.swing.JButton();
        jTxfValorDoc = new javax.swing.JTextField();
        jTxfValorAbatido = new javax.swing.JTextField();
        jTxfRestante = new javax.swing.JTextField();
        jCmbVencimentoRestante = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jTxfCredor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Financeiro Baixa Parcial");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Valor Documento");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Valor Abatido");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Restante");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnCofirma.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jBtnCofirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1Entrar.png"))); // NOI18N
        jBtnCofirma.setText("Confirma");
        jBtnCofirma.setActionCommand("confirmaBaixaParcial");
        jBtnCofirma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnCofirmaKeyPressed(evt);
            }
        });
        jPanel2.add(jBtnCofirma);

        jBtnCancela.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jBtnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jBtnCancela.setText("Cancela");
        jBtnCancela.setActionCommand("cancelaBaixaParcial");
        jPanel2.add(jBtnCancela);

        jTxfValorDoc.setEditable(false);
        jTxfValorDoc.setBackground(new java.awt.Color(255, 255, 255));
        jTxfValorDoc.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfValorDoc.setText("0,00");

        jTxfValorAbatido.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfValorAbatido.setText("0,00");
        jTxfValorAbatido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxfValorAbatidoFocusLost(evt);
            }
        });
        jTxfValorAbatido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfValorAbatidoKeyPressed(evt);
            }
        });

        jTxfRestante.setEditable(false);
        jTxfRestante.setBackground(new java.awt.Color(255, 255, 255));
        jTxfRestante.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfRestante.setText("0,00");

        jCmbVencimentoRestante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbVencimentoRestanteKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Vencimento Restante");

        jTxfCredor.setEditable(false);
        jTxfCredor.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfCredor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbVencimentoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTxfValorAbatido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxfRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxfValorDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jTxfCredor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jTxfCredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jTxfValorDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jTxfValorAbatido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTxfRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jCmbVencimentoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbVencimentoRestanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbVencimentoRestanteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnCofirma.requestFocus();
        }
    }//GEN-LAST:event_jCmbVencimentoRestanteKeyPressed

    private void jTxfValorAbatidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxfValorAbatidoFocusLost
        // TODO add your handling code here:
        jTxfRestante.setText(Uteis.Uteis.formatarMoeda(contasPagar.getVALORPAGO() - Uteis.Uteis.parseDouble(jTxfValorAbatido.getText())));
    }//GEN-LAST:event_jTxfValorAbatidoFocusLost

    private void jTxfValorAbatidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfValorAbatidoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jCmbVencimentoRestante.requestFocus();
        }
    }//GEN-LAST:event_jTxfValorAbatidoKeyPressed

    private void jBtnCofirmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnCofirmaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnCofirma.doClick(0);
        }
    }//GEN-LAST:event_jBtnCofirmaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaixaParcialFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaixaParcialFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaixaParcialFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaixaParcialFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BaixaParcialFrm dialog = new BaixaParcialFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancela;
    private javax.swing.JButton jBtnCofirma;
    private com.toedter.calendar.JDateChooser jCmbVencimentoRestante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxfCredor;
    private javax.swing.JTextField jTxfRestante;
    private javax.swing.JTextField jTxfValorAbatido;
    private javax.swing.JTextField jTxfValorDoc;
    // End of variables declaration//GEN-END:variables

    public void addActionListeners(ActionListener actionListener) {
        jBtnCofirma.addActionListener(actionListener);
        jBtnCancela.addActionListener(actionListener);
    }
    private ContasPagar contasPagar;

    public void setContaPagar(ContasPagar conta) {
        this.contasPagar = conta;
        jTxfValorDoc.setText(Uteis.Uteis.formatarMoeda(conta.getVALORPAGO()));
        jTxfCredor.setText(conta.getCreedor());
        jTxfValorAbatido.grabFocus();
    }

    public ContasPagar getConta() {
        return contasPagar;
    }

    public float getAbatimento() {
        return Uteis.Uteis.parseFloat(jTxfValorAbatido.getText());
    }

    public Date getDataVencimento() {
        return jCmbVencimentoRestante.getDate();
    }
}
