/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.movimento;

import ArrayListComboBoxModel.CategoriaComboBoxModel;
import ArrayListComboBoxModel.TipoContaComboBoxModel;
import ColumnModel.ContasPagarColumnModel;
import TableModel.ContasPagarTableModel;
import bean.cadastro.Categoria;
import bean.cadastro.ContasPagar;
import bean.cadastro.TipoConta;
import Uteis.FieldListener;
import Uteis.FieldListenerFormatandoInteiro;
import Uteis.FieldListneterFormatandoValorMonetario;
import Uteis.UpperCaseLimitado;
import Uteis.UpperCaseParaNumerico;
import Uteis.UpperCaseValores;
import Uteis.ValidarCampos;
import controlefinanceiro.cellEditor.ContasPagarCellEditor;
import java.awt.AWTKeyStroke;
import java.awt.FontMetrics;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Thaigo
 */
public class LancamentoContasFrm extends javax.swing.JDialog {

    /**
     * Creates new form LancamentoContasFrm
     */
    public LancamentoContasFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.getRootPane().getContentPane().setBackground(new java.awt.Color(215, 228, 242));
        jPanel1.setBackground(new java.awt.Color(215, 228, 242));
        jPanel2.setBackground(new java.awt.Color(215, 228, 242));
        jChbJaPAga.setBackground(new java.awt.Color(215, 228, 242));
        jChbTipoLancamento.setBackground(new java.awt.Color(215, 228, 242));
        jTxfCreedor.setDocument(new UpperCaseLimitado(45));
        jTxfCreedor.addFocusListener(new FieldListener());

        jTxfValorCompra.setDocument(new UpperCaseValores(12));
        jTxfValorCompra.addFocusListener(new FieldListneterFormatandoValorMonetario());
//        jTxfDesconto.setDocument(new UpperCaseValores(12));
//        jTxfDesconto.addFocusListener(new FieldListneterFormatandoValorMonetario());
        jTxfValorPago.setDocument(new UpperCaseValores(12));
        jTxfValorPago.addFocusListener(new FieldListneterFormatandoValorMonetario());

        jTxfVezes.setDocument(new UpperCaseParaNumerico(2));
        
        jTxfParcela.setDocument(new UpperCaseParaNumerico(2));
        jTxfTotalParcelas.setDocument(new UpperCaseParaNumerico(2));
        
        jTxfParcela.addFocusListener(new FieldListenerFormatandoInteiro());
        jTxfTotalParcelas.addFocusListener(new FieldListenerFormatandoInteiro());
        
        jTxfVezes.addFocusListener(new FieldListenerFormatandoInteiro());

        jTblParcelas.setAutoCreateColumnsFromModel(false);
        FontMetrics fm = jTblParcelas.getFontMetrics(jTblParcelas.getFont());
        jTblParcelas.setColumnModel(new ContasPagarColumnModel(fm));
        jTblParcelas.getSelectionModel().addListSelectionListener(jTblParcelas);
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "escape");
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
        jTxfCreedor.requestFocus();

        HashSet dataCompra = new HashSet(jCmbDataCompra.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        dataCompra.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        jCmbDataCompra.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, dataCompra);

        HashSet dataVencimento = new HashSet(jCmbDataVencimento.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        dataVencimento.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        jCmbDataVencimento.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, dataVencimento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxfCreedor = new javax.swing.JTextField();
        jCmbCategoria = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxfValorCompra = new javax.swing.JTextField();
        jTxfValorPago = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxfVezes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCmbTipoDeConta = new javax.swing.JComboBox();
        jChbJaPAga = new javax.swing.JCheckBox();
        jCmbDataVencimento = new com.toedter.calendar.JDateChooser();
        jCmbDataCompra = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblParcelas = new javax.swing.JTable();
        jChbTipoLancamento = new javax.swing.JCheckBox();
        jTxfParcela = new javax.swing.JTextField();
        jTxfTotalParcelas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBtnNovo = new javax.swing.JButton();
        jBtnGerarParcelas = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Financeiro Lançamento de Contas");
        setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Creedor");

        jTxfCreedor.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfCreedor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxfCreedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfCreedorKeyPressed(evt);
            }
        });

        jCmbCategoria.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jCmbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmbCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbCategoriaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Categoria");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Data Compra");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Data Vencimento");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Valor Compra");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Valor Pago");

        jTxfValorCompra.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfValorCompra.setText("0,00");
        jTxfValorCompra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxfValorCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxfValorCompraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxfValorCompraFocusLost(evt);
            }
        });
        jTxfValorCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfValorCompraKeyPressed(evt);
            }
        });

        jTxfValorPago.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfValorPago.setText("0,00");
        jTxfValorPago.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTxfValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxfValorPagoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxfValorPagoFocusLost(evt);
            }
        });
        jTxfValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfValorPagoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxfValorPagoKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("Tipo Lançamento");

        jTxfVezes.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfVezes.setText("1");
        jTxfVezes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfVezesKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Parcelas");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("Tipo Conta");

        jCmbTipoDeConta.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jCmbTipoDeConta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmbTipoDeConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbTipoDeContaKeyPressed(evt);
            }
        });

        jChbJaPAga.setText("Já Paga");
        jChbJaPAga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jChbJaPAgaKeyPressed(evt);
            }
        });

        jCmbDataVencimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbDataVencimentoKeyPressed(evt);
            }
        });

        jCmbDataCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbDataCompraKeyPressed(evt);
            }
        });

        jTblParcelas.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTblParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblParcelas.setRowHeight(20);
        jScrollPane1.setViewportView(jTblParcelas);

        jChbTipoLancamento.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jChbTipoLancamento.setText("Pagamento / Débito");
        jChbTipoLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jChbTipoLancamentoKeyPressed(evt);
            }
        });

        jTxfParcela.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfParcela.setText("0");
        jTxfParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfParcelaKeyPressed(evt);
            }
        });

        jTxfTotalParcelas.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTxfTotalParcelas.setText("0");
        jTxfTotalParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxfTotalParcelasKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel13.setText("Parcela");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setText("Parcelas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxfCreedor)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jCmbDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jCmbDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxfVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbJaPAga))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jTxfValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(142, 142, 142)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTxfValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jChbTipoLancamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jCmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbTipoDeConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(22, 22, 22))
                                            .addComponent(jTxfParcela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxfTotalParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(2, 2, 2))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTxfValorCompra, jTxfValorPago});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jTxfCreedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTxfVezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbJaPAga)
                            .addComponent(jCmbDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jChbTipoLancamento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbTipoDeConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxfValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxfTotalParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(2, 2, 2)
                        .addComponent(jTxfParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mais.png"))); // NOI18N
        jBtnNovo.setText("Novo");
        jBtnNovo.setActionCommand("lancarNovaConta");
        jPanel2.add(jBtnNovo);

        jBtnGerarParcelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atualiza.png"))); // NOI18N
        jBtnGerarParcelas.setText("Gerar");
        jBtnGerarParcelas.setActionCommand("gerarParcelas");
        jBtnGerarParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnGerarParcelasKeyPressed(evt);
            }
        });
        jPanel2.add(jBtnGerarParcelas);

        jBtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salvar.png"))); // NOI18N
        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setActionCommand("salvarConta");
        jBtnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnSalvarKeyPressed(evt);
            }
        });
        jPanel2.add(jBtnSalvar);

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setActionCommand("excluirConta");
        jPanel2.add(jBtnExcluir);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lançar Conta.png"))); // NOI18N
        jLabel12.setText("Lançamento de Contas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxfValorCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxfValorCompraFocusLost
        // TODO add your handling code here:
        jTxfValorCompra.setText(Uteis.Uteis.formatarMoeda(jTxfValorCompra.getText()));
    }//GEN-LAST:event_jTxfValorCompraFocusLost

    private void jTxfValorPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxfValorPagoFocusLost
        // TODO add your handling code here:
        jTxfValorPago.setText(Uteis.Uteis.formatarMoeda(jTxfValorPago.getText()));
    }//GEN-LAST:event_jTxfValorPagoFocusLost

    private void jTxfCreedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfCreedorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jCmbDataCompra.requestFocus();
        }
    }//GEN-LAST:event_jTxfCreedorKeyPressed

    private void jCmbCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbCategoriaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jCmbTipoDeConta.requestFocus();
        }
    }//GEN-LAST:event_jCmbCategoriaKeyPressed

    private void jTxfValorCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfValorCompraKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxfValorPago.requestFocus();
        }
    }//GEN-LAST:event_jTxfValorCompraKeyPressed

    private void jTxfValorPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfValorPagoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxfValorPagoKeyReleased

    private void jTxfValorPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfValorPagoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxfParcela.requestFocus();

        }
    }//GEN-LAST:event_jTxfValorPagoKeyPressed

    private void jBtnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnSalvarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnSalvar.doClick();
        }
    }//GEN-LAST:event_jBtnSalvarKeyPressed

    private void jTxfValorCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxfValorCompraFocusGained
        // TODO add your handling code here:
        jTxfValorCompra.selectAll();
    }//GEN-LAST:event_jTxfValorCompraFocusGained

    private void jTxfValorPagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxfValorPagoFocusGained
        // TODO add your handling code here:
        jTxfValorPago.selectAll();
    }//GEN-LAST:event_jTxfValorPagoFocusGained

    private void jCmbTipoDeContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbTipoDeContaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxfValorCompra.requestFocus();
        }
    }//GEN-LAST:event_jCmbTipoDeContaKeyPressed

    private void jTxfVezesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfVezesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jChbJaPAga.requestFocus();
        }
    }//GEN-LAST:event_jTxfVezesKeyPressed

    private void jChbJaPAgaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jChbJaPAgaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jChbTipoLancamento.requestFocus();
        }
    }//GEN-LAST:event_jChbJaPAgaKeyPressed

    private void jCmbDataVencimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbDataVencimentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxfVezes.requestFocus();
        }
    }//GEN-LAST:event_jCmbDataVencimentoKeyPressed

    private void jCmbDataCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbDataCompraKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbDataCompraKeyPressed

    private void jBtnGerarParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnGerarParcelasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnGerarParcelas.doClick(0);
        }
    }//GEN-LAST:event_jBtnGerarParcelasKeyPressed

    private void jChbTipoLancamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jChbTipoLancamentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jCmbCategoria.requestFocus();
        }
    }//GEN-LAST:event_jChbTipoLancamentoKeyPressed

    private void jTxfTotalParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfTotalParcelasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (jBtnGerarParcelas.isEnabled()) {
                jBtnGerarParcelas.requestFocus();
            } else {
                jBtnSalvar.requestFocus();
            }
        }
    }//GEN-LAST:event_jTxfTotalParcelasKeyPressed

    private void jTxfParcelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfParcelaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxfTotalParcelas.requestFocus();
        }
    }//GEN-LAST:event_jTxfParcelaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancamentoContasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancamentoContasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancamentoContasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancamentoContasFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LancamentoContasFrm dialog = new LancamentoContasFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnGerarParcelas;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JCheckBox jChbJaPAga;
    private javax.swing.JCheckBox jChbTipoLancamento;
    private javax.swing.JComboBox jCmbCategoria;
    private com.toedter.calendar.JDateChooser jCmbDataCompra;
    private com.toedter.calendar.JDateChooser jCmbDataVencimento;
    private javax.swing.JComboBox jCmbTipoDeConta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblParcelas;
    private javax.swing.JTextField jTxfCreedor;
    private javax.swing.JTextField jTxfParcela;
    private javax.swing.JTextField jTxfTotalParcelas;
    private javax.swing.JTextField jTxfValorCompra;
    private javax.swing.JTextField jTxfValorPago;
    private javax.swing.JTextField jTxfVezes;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ActionListener listener) {
        jBtnExcluir.addActionListener(listener);
        jBtnNovo.addActionListener(listener);
        jBtnSalvar.addActionListener(listener);
        jBtnGerarParcelas.addActionListener(listener);
    }

    private ContasPagar conta;

//    private void setHabilitaBotoes(boolean creedor, boolean dataCompra,
//            boolean dataVenciamento, boolean categoria,
//            boolean valorCompra, boolean juros,
//            boolean valorPago, boolean novo,
//            boolean salvar, boolean excluir, boolean tipoConta) {
//        jTxfCreedor.setEnabled(creedor);
//        jCmbDataCompra.setEnabled(dataCompra);
//        jCmbDataVencimento.setEnabled(dataVenciamento);
//        jCmbCategoria.setEnabled(categoria);
//        jTxfValorCompra.setEnabled(valorCompra);
////        jTxfDesconto.setEnabled(juros);
//        jTxfValorPago.setEnabled(valorPago);
//        jBtnNovo.setEnabled(novo);
//        jBtnSalvar.setEnabled(salvar);
//        jBtnExcluir.setEnabled(excluir);
//        jChbTipoLancamento.setEnabled(tipoConta);
//    }
    private CategoriaComboBoxModel categoriaComboBoxModel;

    public void setListaCategoria(List lsetCategoria) {
        Collections.sort(lsetCategoria, new Categoria());
        categoriaComboBoxModel = new CategoriaComboBoxModel(lsetCategoria);
        jCmbCategoria.setModel(categoriaComboBoxModel);
    }

    public Categoria getCategoria() {
        if (jCmbCategoria.getSelectedIndex() == -1) {
            return new Categoria();
        }
        return categoriaComboBoxModel.getCategoriaSelecionada(jCmbCategoria.getSelectedIndex());
    }

    public TipoConta getTipoConta() {
        if (jCmbTipoDeConta.getSelectedIndex() == -1) {
            return new TipoConta();
        }
        return tipoContaComboBoxModel.getTipoConta(jCmbTipoDeConta.getSelectedIndex());
    }
    TipoContaComboBoxModel tipoContaComboBoxModel;

    public void setListaTipoConta(List<TipoConta> lstTipoConta) {
        Collections.sort(lstTipoConta, new TipoConta());
        tipoContaComboBoxModel = new TipoContaComboBoxModel(lstTipoConta);
        jCmbTipoDeConta.setModel(tipoContaComboBoxModel);
    }

    public ContasPagar getConta() throws Exception {
        if (jTxfCreedor.getText().isEmpty()) {
            jTxfCreedor.requestFocus();
            throw new Exception("Digite o nome do Creedor!");
        }
        if (Integer.valueOf(jTxfVezes.getText()) <= 0) {
            jTxfVezes.requestFocus();
            throw new Exception("Informe  a quantidade de parcelas!");
        }
        conta.setJAPAGA(jChbJaPAga.isSelected() ? 'S' : 'N');
        conta.setCreedor(jTxfCreedor.getText());
        conta.setDataCompra(jCmbDataCompra.getCalendar().getTime());
        conta.setDataVenc(jCmbDataVencimento.getCalendar().getTime());
        conta.setCategoria(getCategoria());
        conta.setVALORCOMPRA(Uteis.Uteis.parseFloat(jTxfValorCompra.getText()));
        conta.setParcela(ValidarCampos.getValorCampo(jTxfParcela));
        conta.setTotalParcelas(ValidarCampos.getValorCampo(jTxfTotalParcelas));
//        conta.setDESCONTO(Uteis.Uteis.parseFloat(jTxfDesconto.getText()));
        conta.setVALORPAGO(Uteis.Uteis.parseFloat(jTxfValorPago.getText()));
        conta.atualizarAndamento();
        conta.setTipoConta(getTipoConta());
        if (jChbTipoLancamento.isSelected()) {
            conta.setCOD_OPERACAO(2);
            conta.setOPERACAO("PAGAMENTO");
        } else {
            conta.setCOD_OPERACAO(1);
            conta.setOPERACAO("RECEBIMENTO");
        }
        return conta;
    }

    public void setConta(ContasPagar conta) {
        this.conta = conta;
        jTxfCreedor.setText(conta.getCreedor());
        jCmbDataCompra.setDate(conta.getDataCompra());
        jCmbDataVencimento.setDate(conta.getDataVenc());
        jTxfValorCompra.setText(Uteis.Uteis.formatarMoeda(conta.getVALORCOMPRA()));
        jTxfParcela.setText(String.valueOf(conta.getParcela()));
        jTxfTotalParcelas.setText(String.valueOf(conta.getTotalParcelas()));
//        jTxfDesconto.setText(Uteis.Uteis.formatarMoeda(conta.getDESCONTO()));
        jTxfValorPago.setText(Uteis.Uteis.formatarMoeda(conta.getVALORPAGO()));
        jChbTipoLancamento.setSelected(conta.getCOD_OPERACAO() == 2);
        jCmbCategoria.setSelectedItem(conta.getCategoria().getDescricaoCategoria() + "");

        jCmbTipoDeConta.setSelectedItem(conta.getTipoConta().getDescricao() + "");
        if (jTxfVezes.getText().isEmpty() || "0".equals(jTxfVezes.getText())) {
            jTxfVezes.setText("1");
        }
        jChbJaPAga.setSelected('S' == conta.getJAPAGA());
        jBtnGerarParcelas.setEnabled(conta.getCODIGO() == 0);
        jBtnExcluir.setEnabled(conta.getCODIGO() > 0);
    }

    public int getVezes() {
        if (jTxfVezes.getText().equals("")) {
            jTxfVezes.setText("1");
        }
        return ValidarCampos.getValorCampo(jTxfVezes);
    }

    public void setListaContasPagar(List<ContasPagar> lst) {
        jTblParcelas.setModel(new ContasPagarTableModel(lst));
        jTblParcelas.setDefaultEditor(ContasPagar.class, new ContasPagarCellEditor());
    }
}
