/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * movimentoVeiculo.java
 *
 * Created on 22/01/2011, 22:11:02
 */

package view.movimento;

import view.Cadastro.selecionaVeicMovimento;
import Uteis.CalendarComboBox;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrador
 */
public class movimentoVeiculo extends javax.swing.JFrame {
    /** Creates new form movimentoVeiculo */
    public movimentoVeiculo() {
        initComponents();
         CBDataAbastecimento.setSelectedItem(CBDataAbastecimento.getSelectedItem());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBPesquisar = new javax.swing.JButton();
        TAPlaca = new javax.swing.JTextField();
        TACod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TAKM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TAVeic = new javax.swing.JTextField();
        TAVeiculo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TAValorAbastecido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TAValorLT = new javax.swing.JTextField();
        CBPetroleo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TAQuantidadeAbastecido = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TAKMAbastecimento = new javax.swing.JTextField();
        CBDataAbastecimento = new CalendarComboBox(true);
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JBNovo = new javax.swing.JButton();
        JBSalvar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JBDelete = new javax.swing.JButton();
        JBAnterior = new javax.swing.JButton();
        JBProximo = new javax.swing.JButton();
        JBPrimeiroRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimentaçao de Veiculos");

        JBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pesquisar.png"))); // NOI18N
        JBPesquisar.setToolTipText("Pesquisar");
        JBPesquisar.setPreferredSize(new java.awt.Dimension(30, 22));
        JBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPesquisarActionPerformed(evt);
            }
        });

        TAPlaca.setEditable(false);

        jLabel3.setText("Veiculo");

        TAKM.setEditable(false);

        jLabel1.setText("Cod.");

        TAVeic.setEditable(false);

        TAVeiculo.setEditable(false);
        TAVeiculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TAVeiculoFocusGained(evt);
            }
        });

        jLabel4.setText("KM");

        jLabel2.setText("Placa");

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        TAValorAbastecido.setText("0,00");
        TAValorAbastecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAValorAbastecidoActionPerformed(evt);
            }
        });
        TAValorAbastecido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TAValorAbastecidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TAValorAbastecidoFocusLost(evt);
            }
        });

        jLabel7.setText("VL Abastecido");

        TAValorLT.setText("0,00");
        TAValorLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAValorLTActionPerformed(evt);
            }
        });
        TAValorLT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TAValorLTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TAValorLTFocusLost(evt);
            }
        });

        CBPetroleo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Gasolina", "Etanol", "Diesel", "" }));

        jLabel9.setText("QTD");

        TAQuantidadeAbastecido.setText("0,00");
        TAQuantidadeAbastecido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TAQuantidadeAbastecidoFocusLost(evt);
            }
        });

        jLabel6.setText("Valor LT");

        jLabel8.setText("Petroleo");

        jLabel5.setText("km Abast");

        TAKMAbastecimento.setText("0,00");
        TAKMAbastecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAKMAbastecimentoActionPerformed(evt);
            }
        });
        TAKMAbastecimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TAKMAbastecimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TAKMAbastecimentoFocusLost(evt);
            }
        });

        CBDataAbastecimento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CBDataAbastecimento.setToolTipText("Data Final da Pesquisa");
        CBDataAbastecimento.setMinimumSize(new java.awt.Dimension(23, 20));
        CBDataAbastecimento.setPreferredSize(new java.awt.Dimension(28, 18));
        CBDataAbastecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBDataAbastecimentoMouseClicked(evt);
            }
        });
        CBDataAbastecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDataAbastecimentoActionPerformed(evt);
            }
        });

        jLabel10.setText("Data");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBPetroleo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TAValorLT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAKMAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CBDataAbastecimento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TAValorAbastecido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TAQuantidadeAbastecido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TAKMAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBDataAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TAValorLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(TAValorAbastecido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CBPetroleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TAQuantidadeAbastecido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        JBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mais.png"))); // NOI18N
        JBNovo.setToolTipText("Novo Lançamento");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salvar.png"))); // NOI18N
        JBSalvar.setToolTipText("Salvar dados");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancela.png"))); // NOI18N
        JBCancelar.setToolTipText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        JBDelete.setToolTipText("Excluir");

        JBAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Previous.png"))); // NOI18N
        JBAnterior.setToolTipText("Anterior");
        JBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAnteriorActionPerformed(evt);
            }
        });

        JBProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        JBProximo.setToolTipText("Proximo");
        JBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProximoActionPerformed(evt);
            }
        });

        JBPrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atualiza.png"))); // NOI18N
        JBPrimeiroRegistro.setToolTipText("Primeiro registro");
        JBPrimeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPrimeiroRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBDelete)
                .addGap(52, 52, 52)
                .addComponent(JBAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBPrimeiroRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBProximo)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBPrimeiroRegistro)
                    .addComponent(JBAnterior)
                    .addComponent(JBProximo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBNovo)
                        .addComponent(JBSalvar)
                        .addComponent(JBCancelar))
                    .addComponent(JBDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TACod, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TAPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TAVeiculo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TAVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TAKM, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(TACod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TAPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(TAVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TAKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(509, 272));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPesquisarActionPerformed
        // TODO add your handling code here:
        new selecionaVeicMovimento().show();
}//GEN-LAST:event_JBPesquisarActionPerformed

    private void TAVeiculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAVeiculoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TAVeiculoFocusGained

    private void TAValorAbastecidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAValorAbastecidoFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TAValorAbastecidoFocusLost

    private void TAValorLTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAValorLTFocusLost
        // TODO add your handling code here:
     
}//GEN-LAST:event_TAValorLTFocusLost

    private void TAQuantidadeAbastecidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAQuantidadeAbastecidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TAQuantidadeAbastecidoFocusLost

    private void TAKMAbastecimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAKMAbastecimentoFocusLost
        // TODO add your handling code here:
      
      
}//GEN-LAST:event_TAKMAbastecimentoFocusLost

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_JBNovoActionPerformed

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_JBSalvarActionPerformed

    private void TAKMAbastecimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAKMAbastecimentoFocusGained
        // TODO add your handling code here:
        TAKMAbastecimento.selectAll();
    }//GEN-LAST:event_TAKMAbastecimentoFocusGained

    private void TAValorLTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAValorLTFocusGained
        // TODO add your handling code here:
        TAValorLT.selectAll();
    }//GEN-LAST:event_TAValorLTFocusGained

    private void TAKMAbastecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAKMAbastecimentoActionPerformed
        // TODO add your handling code here:
        TAValorLT.requestFocus();
    }//GEN-LAST:event_TAKMAbastecimentoActionPerformed

    private void TAValorLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAValorLTActionPerformed
        // TODO add your handling code here:
        TAValorAbastecido.requestFocus();
    }//GEN-LAST:event_TAValorLTActionPerformed

    private void TAValorAbastecidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TAValorAbastecidoFocusGained
        // TODO add your handling code here:
        TAValorAbastecido.selectAll();
    }//GEN-LAST:event_TAValorAbastecidoFocusGained

    private void TAValorAbastecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAValorAbastecidoActionPerformed
        // TODO add your handling code here:
        CBPetroleo.requestFocus();
    }//GEN-LAST:event_TAValorAbastecidoActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void CBDataAbastecimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBDataAbastecimentoMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_CBDataAbastecimentoMouseClicked

    private void CBDataAbastecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDataAbastecimentoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CBDataAbastecimentoActionPerformed

    private void JBPrimeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPrimeiroRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBPrimeiroRegistroActionPerformed

    private void JBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBProximoActionPerformed

    private void JBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBAnteriorActionPerformed

   /*
    * 
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movimentoVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBDataAbastecimento;
    private javax.swing.JComboBox CBPetroleo;
    private javax.swing.JButton JBAnterior;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBDelete;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JButton JBPrimeiroRegistro;
    private javax.swing.JButton JBProximo;
    private javax.swing.JButton JBSalvar;
    public static javax.swing.JTextField TACod;
    public static javax.swing.JTextField TAKM;
    private javax.swing.JTextField TAKMAbastecimento;
    public static javax.swing.JTextField TAPlaca;
    private javax.swing.JFormattedTextField TAQuantidadeAbastecido;
    private javax.swing.JTextField TAValorAbastecido;
    private javax.swing.JTextField TAValorLT;
    public static javax.swing.JTextField TAVeic;
    public static javax.swing.JTextField TAVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}